{
 "title": "Worker",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"worker-server\"}"
    }
   ]
  },
  {
   "title": "Worker Start Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_start_time_seconds{}" }
   ]
  },
  {
   "title": "Worker Submit Queue Full/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(ds_worker_full_submit_queue_count_total{}[1m])"
    }
   ]
  },
  {
   "title": "Worker Overload Increase/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "increase(ds_worker_overload_count_total{}[1m])"
    }
   ]
  },
  {
   "title": "Worker Running Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "targets": [
    { "expr": "ds_task_running{}" }
   ]
  },
  {
   "title": "Task Total Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_task_execution_count_total)"
    }
   ]
  },
  {
   "title": "Task Successful Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_task_execution_count_total{result=\"success\"}) / sum(ds_task_execution_count_total) * 100"
    }
   ]
  },
  {
   "title": "Task Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "millse" } },
   "yaxes": [
    { "format": "millse" }
   ],
   "targets": [
    {
     "expr": "rate(ds_task_execution_duration_seconds_sum[1m])/rate(ds_task_execution_duration_seconds_count[1m])",
     "legendFormat": "avg ({{exception}})"
    },
    {
     "expr": "ds_task_execution_duration_seconds_max",
     "legendFormat": "max ({{exception}})"
    }
   ]
  },
  {
   "title": "Task Execution Total/Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_total[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(ds_task_execution_count_total{result=\"success\"}[1m])",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Worker Resource Download Count/5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(ds_worker_resource_download_count_total{}[5m]))"
    },
    {
     "expr": "increase(ds_worker_resource_download_count_total{status=\"success\"}[5m])"
    },
    {
     "expr": "increase(ds_worker_resource_download_count_total{status=\"fail\"}[5m])"
    }
   ]
  },
  {
   "title": "Worker Resource Download Time/5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "increase(ds_worker_resource_download_duration_seconds{}[5m])"
    }
   ]
  },
  {
   "title": "Worker Resource Download Size/5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "increase(ds_worker_resource_download_size_bytes[5m])"
    }
   ]
  },
  {
   "title": "Worker Resource Download Size Distribution/5m",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(increase(ds_worker_resource_download_size_bytes_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Worker Resource Download Time Distribution/5m",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ds_worker_resource_download_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  { "title": "Task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "ZEPPELIN Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"ZEPPELIN\"}[1d]))",
     "legendFormat": "DEPENDENT"
    }
   ]
  },
  {
   "title": "JUPYTER Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"JUPYTER\"}[1d]))",
     "legendFormat": "DEPENDENT"
    }
   ]
  },
  {
   "title": "Shell Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"SHELL\"}[1d]))",
     "legendFormat": "SHELL"
    }
   ]
  },
  {
   "title": "Unkown Task Execution Total/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"unknown\"}[1d]))",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "DATA_QUALITY Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"DATA_QUALITY\"}[1d]))",
     "legendFormat": "DATA_QUALITY"
    }
   ]
  },
  {
   "title": "Blocking Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"BLOCKING\"}[1d]))",
     "legendFormat": "BLOCKING"
    }
   ]
  },
  {
   "title": "DATAX Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 74 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"DATAX\"}[1d]))",
     "legendFormat": "DATAX"
    }
   ]
  },
  {
   "title": "EMR Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 74 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"EMR\"}[1d]))",
     "legendFormat": "EMR"
    }
   ]
  },
  {
   "title": "DATA_QUALITY Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"DATA_QUALITY\"}[1d]))",
     "legendFormat": "DATA_QUALITY"
    }
   ]
  },
  {
   "title": "DATA_QUALITY Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"DATA_QUALITY\"}[1d]))",
     "legendFormat": "DATA_QUALITY"
    }
   ]
  },
  {
   "title": "Condition Task Execution Total/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 82 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_execution_count_by_type_total{task_type=\"CONDITIONS\"}[1d]))",
     "legendFormat": "CONDITIONS"
    }
   ]
  }
 ]
}